# Generated by Django 4.1.10 on 2023-08-10 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=100)),
                ('waypoint_data', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=50)),
            ],
        ),
    ]
